# Generated by Django 2.2.3 on 2019-07-28 10:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y%m/%d/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
