# Generated by Django 2.2.3 on 2019-07-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_experience_project_projectimage_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='blog',
            new_name='project',
        ),
    ]
