# Generated by Django 2.2.3 on 2019-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='acad/%Y%m/%d/'),
        ),
    ]
